import json
from infra.memory import find_similar_memories
from core.provider import chat_with_deepseek
from infra.db import add_memory, memory_exists, update_memory
from infra.llm_output import parse_llm_json_array, parse_llm_json_object


ALLOWED_MEMORY_TYPES = {"fact", "preference", "reference"}
ALLOWED_MERGE_ACTIONS = {"skip", "replace", "keep_both"}

REFERENCE_PROMPT = """
你是一个记忆提取助手。请从下面的对话中提取长期有价值的记忆。

只允许使用以下 memory_type：
- fact：长期事实，例如用户身份、项目、技术栈、研究方向
- preference：用户偏好，例如讲解风格、沟通方式、开发节奏
- reference：参考背景，例如用户提到的资料、论文、课程、已有项目

请只输出 JSON 数组，不要输出 Markdown，不要输出解释。
每个元素必须包含 memory_type 和 content 两个字段。

示例：
[
  {{"memory_type": "fact", "content": "用户正在开发 mini-coder 项目"}},
  {{"memory_type": "preference", "content": "用户希望讲解代码时节奏慢一点"}}
]

如果对话中没有值得长期保存的记忆，请输出：
[]

对话内容：
{conversation_history}
"""

MERGE_DECISION_PROMPT = """
你是一个记忆合并判断助手。请判断新记忆和相似旧记忆之间的关系。

允许的 action 只有三个：
- skip：新记忆和某条旧记忆重复，不需要新增
- replace：新记忆比某条旧记忆更具体或更新，后续应该替换旧记忆
- keep_both：新记忆和旧记忆都应该保留
判断时请参考相似旧记忆中的时间和使用字段：
- created_at：旧记忆第一次创建时间
- updated_at：旧记忆最近一次被修正或替换的时间
- last_used_at：旧记忆最近一次被注入上下文的时间
- access_count：旧记忆被注入上下文的次数

如果新记忆明显比旧记忆更新、更具体，可以选择 replace。
如果旧记忆经常被使用，且新记忆只是轻微改写，请谨慎 replace。
如果新旧记忆表达的是不同事实，请选择 keep_both。
请只输出 JSON 对象，不要输出 Markdown，不要输出解释。
格式如下：
{{
  "action": "skip | replace | keep_both",
  "target_content": "被命中的旧记忆 content；如果 action 是 keep_both，则为 null",
  "reason": "一句话说明原因"
}}

新记忆：
{new_memory}

相似旧记忆：
{similar_memories}
"""


def _default_merge_decision(reason: str = "Invalid merge decision") -> dict:
    return {
        "action": "keep_both",
        "target_content": None,
        "reason": reason,
    }


def parse_typed_memories(raw_text: str) -> list[dict[str, str]]:
    """Parse and validate typed memories generated by the LLM."""
    text = raw_text.strip()
    if not text or text in {"无", "none", "None", "null", "NULL"}:
        return []

    data = parse_llm_json_array(text)
    if data is None:
        return []

    memories: list[dict[str, str]] = []
    for item in data:
        if not isinstance(item, dict):
            continue

        memory_type = str(item.get("memory_type", "")).strip().lower()
        content = str(item.get("content", "")).strip()

        if memory_type not in ALLOWED_MEMORY_TYPES:
            continue
        if not content or content in {"无", "none", "None", "null", "NULL"}:
            continue

        memories.append({"memory_type": memory_type, "content": content})

    return memories


def parse_merge_decision(raw_text: str, similar_memories: list[dict]) -> dict:
    """Parse and validate an LLM memory-merge decision."""
    data = parse_llm_json_object(raw_text)
    if data is None:
        return _default_merge_decision()

    action = str(data.get("action", "")).strip().lower()
    if action not in ALLOWED_MERGE_ACTIONS:
        return _default_merge_decision(f"Invalid action: {action}")

    reason = str(data.get("reason", "")).strip()
    target_content = data.get("target_content")
    candidate_contents = {memory.get("content") for memory in similar_memories}

    if action == "keep_both":
        return {
            "action": "keep_both",
            "target_content": None,
            "reason": reason,
        }

    if target_content not in candidate_contents:
        return _default_merge_decision("Target content is not in similar memories")

    return {
        "action": action,
        "target_content": target_content,
        "reason": reason,
    }


def decide_memory_merge(new_memory: dict, similar_memories: list[dict]) -> dict:
    """Ask the LLM whether a new memory should be skipped, replaced, or kept."""
    if not similar_memories:
        return _default_merge_decision("No similar memories")

    prompt = MERGE_DECISION_PROMPT.format(
        new_memory=json.dumps(new_memory, ensure_ascii=False),
        similar_memories=json.dumps(similar_memories, ensure_ascii=False),
    )
    resp = chat_with_deepseek([{"role": "user", "content": prompt}])
    raw_result = resp.choices[0].message.content or ""
    return parse_merge_decision(raw_result, similar_memories)


def _find_merge_target(decision: dict, similar_memories: list[dict]) -> dict | None:
    """Find the existing memory selected by a validated merge decision."""
    target_content = decision.get("target_content")
    for memory in similar_memories:
        if memory.get("content") == target_content:
            return memory
    return None


def reflect(conversation_id: int, messages: list[dict]) -> list[dict[str, str]]:
    """Extract typed memories from a conversation and store valid ones."""
    conv_text = "\n".join(
        f"{'用户' if m.get('role') == 'user' else '助手'}: {m.get('content', '')}"
        for m in messages
        if isinstance(m, dict) and m.get("role") in ("user", "assistant")
    )

    reflect_prompt = REFERENCE_PROMPT.format(conversation_history=conv_text)
    reflect_messages = [{"role": "user", "content": reflect_prompt}]

    resp = chat_with_deepseek(reflect_messages)
    raw_result = resp.choices[0].message.content or ""
    memories = parse_typed_memories(raw_result)

    stored_memories = []
    for memory in memories:
        if memory_exists(memory["content"], memory["memory_type"]):
            continue

        similar_memories = find_similar_memories(
            content=memory["content"],
            memory_type=memory["memory_type"],
            k=3,
            min_score=0.75,
        )
        decision = decide_memory_merge(memory, similar_memories)

        if decision["action"] == "skip":
            continue

        if decision["action"] == "replace":
            target_memory = _find_merge_target(decision, similar_memories)
            if target_memory is not None:
                update_memory(
                    memory_id=target_memory["id"],
                    content=memory["content"],
                    embedding=None,
                    memory_type=memory["memory_type"],
                )
                stored_memories.append(memory)
                continue

        add_memory(
            conversation_id=conversation_id,
            content=memory["content"],
            embedding=None,
            memory_type=memory["memory_type"],
        )
        stored_memories.append(memory)

    return stored_memories
