import json

from core.provider import chat_with_deepseek
from infra.db import add_memory, memory_exists


ALLOWED_MEMORY_TYPES = {"fact", "preference", "reference"}

REFERENCE_PROMPT = """
你是一个记忆提取助手。请从下面的对话中提取长期有价值的记忆。

只允许使用以下 memory_type：
- fact：长期事实，例如用户身份、项目、技术栈、研究方向
- preference：用户偏好，例如讲解风格、沟通方式、开发节奏
- reference：参考背景，例如用户提到的资料、论文、课程、已有项目

请只输出 JSON 数组，不要输出 Markdown，不要输出解释。
每个元素必须包含 memory_type 和 content 两个字段。

示例：
[
  {{"memory_type": "fact", "content": "用户正在开发 mini-coder 项目"}},
  {{"memory_type": "preference", "content": "用户希望讲解代码时节奏慢一点"}}
]

如果对话中没有值得长期保存的记忆，请输出：
[]

对话内容：
{conversation_history}
"""


def _normalize_llm_json(raw_text: str) -> str:
    """Return the JSON-looking part of an LLM response."""
    text = raw_text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    start = text.find("[")
    end = text.rfind("]")
    if start != -1 and end != -1 and start <= end:
        return text[start : end + 1]
    return text


def parse_typed_memories(raw_text: str) -> list[dict[str, str]]:
    """Parse and validate typed memories generated by the LLM."""
    text = raw_text.strip()
    if not text or text in {"无", "none", "None", "null", "NULL"}:
        return []

    try:
        data = json.loads(_normalize_llm_json(text))
    except json.JSONDecodeError:
        return []

    if not isinstance(data, list):
        return []

    memories: list[dict[str, str]] = []
    for item in data:
        if not isinstance(item, dict):
            continue

        memory_type = str(item.get("memory_type", "")).strip().lower()
        content = str(item.get("content", "")).strip()

        if memory_type not in ALLOWED_MEMORY_TYPES:
            continue
        if not content or content in {"无", "none", "None", "null", "NULL"}:
            continue

        memories.append({"memory_type": memory_type, "content": content})

    return memories


def reflect(conversation_id: int, messages: list[dict]) -> list[dict[str, str]]:
    """Extract typed memories from a conversation and store valid ones."""
    conv_text = "\n".join(
        f"{'用户' if m.get('role') == 'user' else '助手'}: {m.get('content', '')}"
        for m in messages
        if isinstance(m, dict) and m.get("role") in ("user", "assistant")
    )

    reflect_prompt = REFERENCE_PROMPT.format(conversation_history=conv_text)
    reflect_messages = [{"role": "user", "content": reflect_prompt}]

    resp = chat_with_deepseek(reflect_messages)
    raw_result = resp.choices[0].message.content or ""
    memories = parse_typed_memories(raw_result)

    stored_memories = []
    for memory in memories:
        if memory_exists(memory["content"], memory["memory_type"]):
            continue
        add_memory(
            conversation_id = conversation_id,
            content = memory["content"],
            embedding = None,
            memory_type = memory["memory_type"],
        )
        stored_memories.append(memory)

    return stored_memories
